print(int(input("Please enter integer: "))) 
print(bool(input("Please enter bool: "))) 
print(float(input("Please enter float: ")))
print(str(input("Please enter string: "))) 
print(int(input("Please enter integer: "))) 
print(bool(input("Please enter bool: "))) 
print(float(input("Please enter float: ")))
print(str(input("Please enter string: "))) 
print(int(input("Please enter integer: "))) 
print(bool(input("Please enter bool: "))) 
print(float(input("Please enter float: ")))
print(str(input("Please enter string: "))) 
print(int(input("Please enter integer: "))) 
print(bool(input("Please enter bool: "))) 
print(float(input("Please enter float: ")))
print(str(input("Please enter string: "))) 
print(int(input("Please enter integer: "))) 
print(bool(input("Please enter boll: "))) 
print(float(input("Please enter float: ")))
print(str(input("Please enter string: "))) 
#2nd part of homework
num1 = (int(input("Please enter integer: ")))
num2 = (int(input("Please enter integer:")))
num3 = (int(input("Please enter integer:")))
num4 = (int(input("Please enter integer:")))
num5 = (int(input("Please enter integer:")))
print(int(num1+num2-num3/num4*num5//num3%num1))